### ISSUE TITLE
[Error] pipeline() got an unexpected keyword argument

### ISSUE THREAD

**Issue by HieronZhang** [pytorch/PiPPy#1134]
Hi, I used the pytorch version 2.5.0.dev20240613+cu124 with python version 3.10.14

When I ran the OPT example "torchrun --nproc-per-node 2 pippy_opt.py", I got this error:

```
[rank0]: Traceback (most recent call last):
[rank0]:   File "/home/zhang402/PiPPy-main/PiPPy/examples/huggingface/pippy_opt.py", line 106, in <module>
[rank0]:     run(args)
[rank0]:   File "/home/zhang402/PiPPy-main/PiPPy/examples/huggingface/pippy_opt.py", line 46, in run
[rank0]:     pipe = pipeline(
[rank0]: TypeError: pipeline() got an unexpected keyword argument 'num_chunks'
```

**Comment by HieronZhang** [comment]
Besides, your basic examples (`basic/example.py` and `basic/example_train.py`) are still using `pippy`, not `torch.distributed.pipelining`, can you update them, thanks! (The `example_train.py` is the only one training example...)
