### ISSUE TITLE
tp+pp and gspmd examples not running

### ISSUE THREAD

**Issue by access2rohit** [pytorch/PiPPy#809]
May machine has 8 GPUs and I am trying to run the examples in directories tp+pp and gspmd

my ENV variables
```
export RANK=-1
export MASTER_ADDR=localhost
export MASTER_PORT=29600
export WORLD_SIZE=8
```

```
pytest pippy_gspmd.py
```
gives Error:
```
ubuntu@ip-<ip> ~/workspace/PiPPy/examples/gspmd (main) $ python pippy_gspmd.py
[PiPPy] World size: 8, DP group size: 1, PP group size: 8
rank = 4 host/pid/device = ip-172-31-1-12/83340/cuda:4
rank = 1 host/pid/device = ip-172-31-1-12/83337/cuda:1
rank = 5 host/pid/device = ip-172-31-1-12/83341/cuda:5
rank = 0 host/pid/device = ip-172-31-1-12/83336/cuda:0
rank = 3 host/pid/device = ip-172-31-1-12/83339/cuda:3
rank = 7 host/pid/device = ip-172-31-1-12/83343/cuda:7
rank = 6 host/pid/device = ip-172-31-1-12/83342/cuda:6
rank = 2 host/pid/device = ip-172-31-1-12/83338/cuda:2
WARNING > Did not find any loss value from model output, your pipeline will be in inference mode. If you want your pipeline to be in training mode, please specify a loss value via `output_loss_value_spec`.
WARNING > Did not find any loss value from model output, your pipeline will be in inference mode. If you want your pipeline to be in training mode, please specify a loss value via `output_loss_value_spec`.
WARNING > Did not find any loss value from model output, your pipeline will be in inference mode. If you want your pipeline to be in training mode, please specify a loss value via `output_loss_value_spec`.
WARNING > Did not find any loss value from model output, your pipeline will be in inference mode. If you want your pipeline to be in training mode, please specify a loss value via `output_loss_value_spec`.
WARNING > Did not find any loss value from model output, your pipeline will be in inference mode. If you want your pipeline to be in training mode, please specify a loss value via `output_loss_value_spec`.
WARNING > Did not find any loss value from model output, your pipeline will be in inference mode. If you want your pipeline to be in training mode, please specify a loss value via `output_loss_value_spec`.
WARNING > Did not find any loss value from model output, your pipeline will be in inference mode. If you want your pipeline to be in training mode, please specify a loss value via `output_loss_value_spec`.
Rank 2: PipeStageModule()



def forward(self, lin, mm):
    moved_mm_param2 = self.moved_mm_param2
    relu = torch.relu(lin);  lin = None
    add = relu + mm;  relu = mm = None
    mm_1 = torch.mm(add, moved_mm_param2);  add = moved_mm_param2 = None
    return mm_1

# To see more debug info, please use `graph_module.print_readable()`
Rank 1: PipeStageModule(
  (lin): Linear(in_features=512, out_features=512, bias=True)
)



def forward(self, relu):
    moved_mm_param = self.moved_mm_param
    moved_buffer = self.moved_buffer
    mm = torch.mm(relu, moved_mm_param);  moved_mm_param = None
    getattr_1 = relu.shape;  relu = None
    getitem = getattr_1[0];  getattr_1 = None
    getitem_1 = moved_buffer[slice(None, getitem, None)];  moved_buffer = getitem = None
    add = mm + getitem_1;  mm = getitem_1 = None
    lin = self.lin(add);  add = None
    return lin

# To see more debug info, please use `graph_module.print_readable()`
Rank 3: PipeStageModule(
  (lin): Linear(in_features=512, out_features=512, bias=True)
)



def forward(self, mm_2):
    lin = self.lin(mm_2);  mm_2 = None
    relu = torch.relu(lin);  lin = None
    return relu

# To see more debug info, please use `graph_module.print_readable()`
WARNING > Did not find any loss value from model output, your pipeline will be in inference mode. If you want your pipeline to be in training mode, please specify a loss value via `output_loss_value_spec`.
/home/ubuntu/workspace/PiPPy/pippy/PipelineDriver.py:1450: UserWarning: Running pipeline with 4 stages on world_size of 8. Remaining ranks will be idle.
  warnings.warn(
Rank 0: PipeStageModule()



def forward(self, x):
    moved_mm_param = self.moved_mm_param
    mm = torch.mm(x, moved_mm_param);  x = moved_mm_param = None
    relu = torch.relu(mm)
    return (relu, mm)

# To see more debug info, please use `graph_module.print_readable()`
[W tensorpipe_agent.cpp:725] RPC agent for worker0 encountered error when reading incoming request from worker6: eof (this error originated at tensorpipe/transport/shm/connection_impl.cc:259)
[W tensorpipe_agent.cpp:725] RPC agent for worker2 encountered error when reading incoming request from worker0: eof (this error originated at tensorpipe/transport/shm/connection_impl.cc:259)
[W tensorpipe_agent.cpp:725] RPC agent for worker1 encountered error when reading incoming request from worker0: eof (this error originated at tensorpipe/transport/shm/connection_impl.cc:259)
[W tensorpipe_agent.cpp:725] RPC agent for worker3 encountered error when reading incoming request from worker0: eof (this error originated at tensorpipe/transport/shm/connection_impl.cc:259)
[W tensorpipe_agent.cpp:725] RPC agent for worker4 encountered error when reading incoming request from worker0: eof (this error originated at tensorpipe/transport/shm/connection_impl.cc:259)
[W tensorpipe_agent.cpp:939] RPC agent for worker1 encountered error when reading incoming response from worker0: eof (this error originated at tensorpipe/transport/shm/connection_impl.cc:259)
[W tensorpipe_agent.cpp:939] RPC agent for worker1 encountered error when reading incoming response from worker0: eof (this error originated at tensorpipe/transport/shm/connection_impl.cc:259)
[W tensorpipe_agent.cpp:939] RPC agent for worker1 encountered error when reading incoming response from worker0: eof (this error originated at tensorpipe/transport/shm/connection_impl.cc:259)
[W tensorpipe_agent.cpp:939] RPC agent for worker2 encountered error when reading incoming response from worker0: eof (this error originated at tensorpipe/transport/shm/connection_impl.cc:259)
[W tensorpipe_agent.cpp:939] RPC agent for worker2 encountered error when reading incoming response from worker0: eof (this error originated at tensorpipe/transport/shm/connection_impl.cc:259)
[W tensorpipe_agent.cpp:725] RPC agent for worker3 encountered error when reading incoming request from worker1: eof (this error originated at tensorpipe/transport/shm/connection_impl.cc:259)
[W tensorpipe_agent.cpp:939] RPC agent for worker2 encountered error when reading incoming response from worker1: eof (this error originated at tensorpipe/transport/shm/connection_impl.cc:259)
[W tensorpipe_agent.cpp:939] RPC agent for worker2 encountered error when reading incoming response from worker1: eof (this error originated at tensorpipe/transport/shm/connection_impl.cc:259)
[W tensorpipe_agent.cpp:725] RPC agent for worker2 encountered error when reading incoming request from worker1: eof (this error originated at tensorpipe/transport/shm/connection_impl.cc:259)
[W tensorpipe_agent.cpp:939] RPC agent for worker3 encountered error when reading incoming response from worker2: eof (this error originated at tensorpipe/transport/shm/connection_impl.cc:259)
[W tensorpipe_agent.cpp:725] RPC agent for worker3 encountered error when reading incoming request from worker2: eof (this error originated at tensorpipe/transport/shm/connection_impl.cc:259)
Traceback (most recent call last):
  File "/home/ubuntu/workspace/PiPPy/examples/gspmd/pippy_gspmd.py", line 113, in <module>
    main()
  File "/home/ubuntu/workspace/PiPPy/examples/gspmd/pippy_gspmd.py", line 109, in main
    run_pippy(run_gspmd, args)
  File "/home/ubuntu/workspace/PiPPy/pippy/utils.py", line 156, in run_pippy
    mp.spawn(
  File "/home/ubuntu/.local/lib/python3.9/site-packages/torch/multiprocessing/spawn.py", line 239, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/home/ubuntu/.local/lib/python3.9/site-packages/torch/multiprocessing/spawn.py", line 197, in start_processes
    while not context.join():
  File "/home/ubuntu/.local/lib/python3.9/site-packages/torch/multiprocessing/spawn.py", line 160, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException:

-- Process 6 terminated with the following error:
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.9/site-packages/torch/multiprocessing/spawn.py", line 69, in _wrap
    fn(i, *args)
  File "/home/ubuntu/workspace/PiPPy/pippy/utils.py", line 280, in run_worker
    run_func(my_pp_ranks, args, *extra_args)
  File "/home/ubuntu/workspace/PiPPy/examples/gspmd/pippy_gspmd.py", line 52, in run_gspmd
    pipe_driver, stage_mod = pippy.all_compile(
  File "/home/ubuntu/workspace/PiPPy/pippy/compile.py", line 198, in all_compile
    return _compile(
  File "/home/ubuntu/workspace/PiPPy/pippy/compile.py", line 114, in _compile
    stage_mod = pipe_model.export(pp_rank)
  File "/home/ubuntu/workspace/PiPPy/pippy/IR.py", line 1128, in export
    submod = split_gm_children[stage_id]
IndexError: list index out of range

```

and 

```
python pippy_tp.py
```
Gives error 
```
(pippy) ubuntu@<ip> ~/workspace/PiPPy/examples/tp+pp (main) $ pytest pippy_tp.py
=============================================================================================== test session starts ================================================================================================
platform linux -- Python 3.9.16, pytest-7.3.2, pluggy-1.0.0
rootdir: /home/ubuntu/workspace/PiPPy
collected 1 item

pippy_tp.py F                                                                                                                                                                                                [100%]

===================================================================================================== FAILURES =====================================================================================================
___________________________________________________________________________________________ LocalTestPiPPyTP.test_pp_tp ____________________________________________________________________________________________

self = <pippy_tp.LocalTestPiPPyTP testMethod=test_pp_tp>

    def test_pp_tp(self):
        import random

        port = random.randint(29500, 30000)
        args = [
            "--master_port",
            str(port),
        ]
>       main(args)

pippy_tp.py:212:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
pippy_tp.py:190: in main
    dist.init_process_group(
../../../../.local/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py:900: in init_process_group
    store, rank, world_size = next(rendezvous_iterator)
../../../../.local/lib/python3.9/site-packages/torch/distributed/rendezvous.py:245: in _env_rendezvous_handler
    store = _create_c10d_store(master_addr, master_port, rank, world_size, timeout)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
hostname = 'localhost', port = 29600, rank = -1, world_size = 8, timeout = datetime.timedelta(seconds=1800)

    def _create_c10d_store(hostname, port, rank, world_size, timeout) -> Store:
        """
        Smartly creates a c10d Store object on ``rank`` based on whether
        we need to re-use agent store. The TCPStore server is assumed to be hosted
        on ``hostname:port``.

        If ``torchelastic_use_agent_store()`` is ``True``, then it is assumed that
        the agent leader (node rank 0) hosts the TCPStore server (for which the
        endpoint is specified by the given ``hostname:port``). Hence
        ALL ranks will create and return a TCPStore client (e.g. ``start_daemon=False``).

        If ``torchelastic_use_agent_store()`` is ``False``, then rank 0 will host
        the TCPStore (with multi-tenancy) and it is assumed that rank 0's hostname
        and port are correctly passed via ``hostname`` and ``port``. All
        non-zero ranks will create and return a TCPStore client.
        """
        # check if port is uint16_t
        if not 0 <= port < 2**16:
            raise ValueError(f"port must have value from 0 to 65535 but was {port}.")

        if _torchelastic_use_agent_store():
            attempt = os.environ["TORCHELASTIC_RESTART_COUNT"]
            tcp_store = TCPStore(hostname, port, world_size, False, timeout)
            return PrefixStore(f"/worker/attempt_{attempt}", tcp_store)
        else:
            start_daemon = rank == 0
>           return TCPStore(
                hostname, port, world_size, start_daemon, timeout, multi_tenant=True
            )
E           TimeoutError: The client socket has timed out after 1800s while trying to connect to (localhost, 29600).

../../../../.local/lib/python3.9/site-packages/torch/distributed/rendezvous.py:176: TimeoutError
----------------------------------------------------------------------------------------------- Captured stderr call -----------------------------------------------------------------------------------------------
[E socket.cpp:860] [c10d] The client socket has timed out after 1800s while trying to connect to (localhost, 29600).
============================================================================================= short test summary info ==============================================================================================
FAILED pippy_tp.py::LocalTestPiPPyTP::test_pp_tp - TimeoutError: The client socket has timed out after 1800s while trying to connect to (localhost, 29600).
========================================================================================== 1 failed in 1801.56s (0:30:01) ==========================================================================================
```

Can someone suggest if I am missing out some input or doing sth wrong ?

**Comment by access2rohit** [comment]
I was able to run it with 
```
torchrun  --nproc-per-node 8 pippy_tp.py
```
and 
```
torchrun  --nproc-per-node 4 pippy_gspmd.py
```

**Comment by access2rohit** [comment]
``
